### ISSUE TITLE
feat: use goreleaser to compile binaries

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/grept#17]
It will help the governance workflows if we can download a pre-compiled binary for grept.

Suggest using goreleaser in a github action to do this when tag is pushed.

WDYT @lonegunmanb?

**Comment by lonegunmanb** [comment]
All MS provided pre-compiled binary MUST be signed with MS's cert, if we'd like to do so we must setup an ADO pipeline, I've tried this process, and trust me, it's not a happy path.

For now I'm satisfied with the status quo, I'd like to give my PM team and leadership a demo, if they decide we should release this tool just like we've done for `aztfexport` and `azapi2azurerm`, then we'll setup this ADO pipeline, and we also need to provide a package to different package manager like `apt`, `choco` etc...

**Comment by matt-FFFFFF** [comment]
Ahhh. I understand. Thank you for looking into it.
