### ISSUE TITLE
feat: `apply` should run `plan` again afterwards to validate the fix

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/grept#20]
Hi @lonegunmanb 

Just like terraform runs a refresh again after applying a resource, I think we should run a plan again after an apply to validate.

Thoughts?

**Comment by matt-FFFFFF** [comment]
For the scenario where we have to rely on an environment variable:

```hcl
rule "must_be_true" {
  condition     = env("GITHUB_REPOSITORY") != ""
  error_message = "Environment variable GITHUB_REPOSITORY must be set. Fixed file content may not be correct."
}
```

There is no fix for this, but we are reliant on this value to populate some file content.

We should run plan again after the fix, so we capture that this is still an issue.

**Comment by matt-FFFFFF** [comment]
Perhaps we could change this line in applyFunc() to call the plan func?

https://github.com/Azure/grept/blob/b2fe2ccce4416ab6d6f4830573fd1abaaae672ce/cmd/apply.go#L79-L80

**Comment by lonegunmanb** [comment]
I think the user can run `plan` command after `apply`. What you described sounds like `precondition` to me, which I think is a good idea. I think I can add a `precondition` for `data`, `rule` and `fix`, WDYT?

**Comment by lonegunmanb** [comment]
I'm closing this issue since now we support `precondition`.
